{
 "title": "Log-Decision",
 "tags": [
  "Log",
  "OPA",
  "PostgreSQL",
  "Kafka"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ingest TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(decision_log_ingest_total[1m])",
     "legendFormat": "Ingest"
    }
   ]
  },
  {
   "title": "Publish TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(decision_log_publish_success_total[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(decision_log_publish_failure_total[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "DB Save TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(decision_log_db_save_success_total[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(decision_log_db_save_failure_total[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "DB Save Retry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(decision_log_db_save_retry_total[1m])",
     "legendFormat": "Retry"
    }
   ]
  },
  {
   "title": "Consume Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(decision_log_consume_process_time_seconds_sum[5m])\n/\nrate(decision_log_consume_process_time_seconds_count[5m])) * 1000\n",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "DLQ / Parking Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(decision_log_dlq_sent_total[5m])\n",
     "legendFormat": "dlq_sent"
    },
    {
     "expr": "rate(decision_log_parking_sent_total[5m])",
     "legendFormat": "parking_sent"
    },
    {
     "expr": "rate(decision_log_parking_recovered_total[5m])\n",
     "legendFormat": "parking_recovered"
    }
   ]
  },
  {
   "title": "E2E Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(decision_log_e2e_latency_seconds_sum[5m])\n/\nrate(decision_log_e2e_latency_seconds_count[5m])) * 1000\n",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}